apiVersion: v1
kind: ConfigMap
metadata:
  name: greendev-config
  labels:
    app: greendev
data:
  APP_PORT: "3000"
  DB_HOST: "db" # Coincide con el Service de la DB
  DB_PORT: "5432"
  DB_USER: "greendev_user"
  DB_NAME: "greendev_db"

---
apiVersion: v1
kind: Secret
metadata:
  name: greendev-secret
  labels:
    app: greendev
type: Opaque
stringData:
  DB_PASSWORD: "secret_example_password"
